### ISSUE TITLE
[feature] allow user to chose where to save completion file to

### ISSUE THREAD

**Issue by deadc0de6** [Infinidat/infi.docopt_completion#20]
Thanks for this very useful tool.

It would be nice if users could provide the output file to write to, would that be possible to add?

Thanks!

**Comment by wiggin15** [comment]
docopt_completion has the flags "--manual-zsh" and "--manual-bash". It's not exactly what you are asking about, but it might be helpful - it outputs the completion file in the local directory only, and then you can move it to where you want. Does that help?

**Comment by deadc0de6** [comment]
Thanks but I wanted to be able to explicitly specify where I want the file to be saved to. Something like `-o --output <file>` for example.
